name: MineReset
main: falkirks\minereset\MineReset
version: 4.0.0-beta
author: Falk & Octopush
api: 4.0.0
load: POSTWORLD
softdepend: [ SimpleWarp ]

permissions:
  minereset:
    default: op
    description: Main permission for mine reset
  minereset.command:
    default: op
    description: Use MineReset commands
  minereset.command.about:
    description: Read the about text
    default: true
  minereset.command.edit:
    description: Use the editor form
    default: op
  minereset.command.report:
    description: Generate github issues
    default: op
  minereset.command.create:
    description: Add new Mines
    default: op
  minereset.command.set:
    description: Set existing mines
    default: op
  minereset.command.reset:
    description: Reset mines
    default: op
  minereset.command.destroy:
    description: Remove mines
    default: op
  minereset.command.resetall:
    description: Reset all mines
    default: op
