name: MineReset
main: falkirks\minereset\MineReset
version: 3.1.0
author: Falk
api: [3.0.0, 4.0.0]
load: POSTWORLD
permissions:
 minereset:
  default: op
  children:
   minereset.command:
    default: op
    description: Use MineReset commands
    children:
      minereset.command.about:
        description: Read the about text
      minereset.command.report:
        description: Generate github issues
      minereset.command.create:
        description: Add new Mines
      minereset.command.set:
        description: Set existing mines
      minereset.command.reset:
        description: Reset mines
      minereset.command.destroy:
        description: Remove mines
      minereset.command.resetall:
        description: Reset all mines
