name: MineReset
main: minereset\MineReset
version: 2.3
author: Falk
api: [1.0.0, 2.0.0, 3.0.0-ALPHA4]
load: POSTWORLD
commands:
 mine:
  description: MineReset command
  usage: /mine < create <name> / set <name> <contents> / reset <name> / destroy <name> / reset-all >
permissions:
 minereset:
  default: op
  children:
   minereset.command:
    default: op
    description: Use MineReset commands
    children:
     minereset.command.create:
      description: Add new Mines
     minereset.command.set:
      description: Set existing mines
     minereset.command.reset:
      description: Reset mines
     minereset.command.destroy:
      description: Remove mines
     minereset.command.reset-all:
      description: Reset all mines
